default_language_version:
  python: python3

exclude: '^.*/migrations/.*$'
fail_fast: true

minimum_pre_commit_version: '1.14.0'

repos:
  # black (code formatting)
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  # isort (automatically sort import statements)
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
  # flake8 (linting)
  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [flake8-bugbear, flake8-docstrings, flake8-django, flake8-assertive]
  # easy regex checks
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      # prohibit blank "noqa"
      - id: python-check-blanket-noqa
      # eval() is evil
      - id: python-no-eval
  # bandit (security issues)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.1
    hooks:
      - id: bandit
  # lint templates
  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: 0.6.8
    hooks:
      - id: djlint-django
  - repo: https://github.com/pycqa/doc8
    rev: 0.10.1
    hooks:
      - id: doc8
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      # check JSON files
      - id: check-json
      # check TOML files
      - id: check-toml
      # check YAML files
      - id: check-yaml
      # let all files end with a single new line (this *should be ensured by
      # .editorconfig already)
      - id: end-of-file-fixer
      # remove all trailing whitespaces (this *should* be ensured by
      # .editorconfig already)
      - id: trailing-whitespace
      # provide uniform line endings for the project ('lf'; this *should be
      # ensured by .editorconfig already)
      - id: mixed-line-ending
        args: [--fix, lf]
      # remove utf-8 byte order marker
      - id: fix-byte-order-marker
